format = """
[](#3b4261)\
[  ](bg:#3b4261 fg:#82aaff)\
[](bg:#82aaff fg:#3b4261)\
$directory\
[](fg:#82aaff bg:#3b4261)\
$git_branch\
$git_status\
[](fg:#3b4261 bg:#222436)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#222436 bg:#3b4261)\
$time\
[ ](fg:#3b4261)\
\n$character"""

[directory]
style = "fg:#3b4261 bg:#82aaff"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#3b4261"
format = '[[ $symbol $branch ](fg:#82aaff bg:#3b4261)]($style)'

[git_status]
style = "bg:#3b4261"
format = '[[($all_status$ahead_behind )](fg:#82aaff bg:#3b4261)]($style)'

[nodejs]
symbol = ""
style = "bg:#222436"
format = '[[ $symbol ($version) ](fg:#82aaff bg:#222436)]($style)'

[rust]
symbol = ""
style = "bg:#222436"
format = '[[ $symbol ($version) ](fg:#82aaff bg:#222436)]($style)'

[golang]
symbol = ""
style = "bg:#222436"
format = '[[ $symbol ($version) ](fg:#82aaff bg:#222436)]($style)'

[php]
symbol = ""
style = "bg:#222436"
format = '[[ $symbol ($version) ](fg:#82aaff bg:#222436)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#3b4261"
format = '[[  $time ](fg:#82aaff bg:#3b4261)]($style)'
